# Generated by Django 4.1.6 on 2023-02-08 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='client',
            name='contact',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
