# Generated by Django 4.1.6 on 2023-02-13 10:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('manifactured_product', '0002_remove_product_code_remove_product_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manifacturedproduct',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='manifacturedproduct',
            name='manufacture_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
