# Generated by Django 4.1.6 on 2023-02-13 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manifactured_product', '0003_manifacturedproduct_active_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ManifacturedProduct',
            new_name='ManufacturedProduct',
        ),
    ]
