# Generated by Django 4.1.6 on 2023-02-13 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manifactured_product', '0004_rename_manifacturedproduct_manufacturedproduct'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manufacturedproduct',
            old_name='price',
            new_name='unit_price',
        ),
    ]
