# Generated by Django 4.1.6 on 2023-02-15 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='name',
            new_name='username',
        ),
        migrations.AddField(
            model_name='employee',
            name='parol',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
