# Generated by Django 4.1.7 on 2023-04-11 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_rename_parol_employee_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(choices=[('1', 'Agent'), ('2', 'Factory worker')], max_length=1),
        ),
        migrations.DeleteModel(
            name='Position',
        ),
    ]
