# Generated by Django 4.1.6 on 2023-02-13 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
        ('client', '0002_remove_client_phone_number_client_contact'),
        ('manifactured_product', '0004_rename_manifacturedproduct_manufacturedproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_order', models.FloatField()),
                ('unit_price', models.CharField(max_length=30)),
                ('total_price', models.FloatField()),
                ('total_discount', models.FloatField()),
                ('discount', models.FloatField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manifactured_product.product')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('0', 'UZS'), ('1', 'RUB'), ('2', 'USD')], max_length=1)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.client')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.productorder')),
            ],
        ),
    ]
