# Generated by Django 4.1.6 on 2023-02-13 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_amount_order_order_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='currency',
            field=models.CharField(choices=[('0', 'UZS'), ('1', 'RUB'), ('2', 'USD')], default=0, max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('0', 'CASH'), ('1', 'BANK CARD'), ('2', 'TRANSFER')], max_length=1),
        ),
    ]
