# Generated by Django 4.1.6 on 2023-02-13 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_remove_order_unit_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_price_discaunt',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
