# Generated by Django 4.1.6 on 2023-02-13 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_order_total_price_discaunt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='total_price_discaunt',
            new_name='total_price_with_discaunt',
        ),
    ]
