# Generated by Django 4.1.7 on 2023-03-27 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_rename_total_price_discaunt_order_total_price_with_discaunt'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='unit_price',
            field=models.CharField(default=12, max_length=30),
            preserve_default=False,
        ),
    ]
